#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += lq101r1sx01a_wqxga_dsi_vdo.o lcm_drv_lq101r1sx01a_wqxga_dsi_vdo.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
